- name: Ensure mysql is running and starts on boot
  service:
    name: mysql
    state: started
    enabled: yes
  become: yes

- name: Create `/root/.my.cnf`  with root password credentials
  template:
    src:  my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  become: yes
  notify: restart mysql

- name: Upload `Qiliasmaster.sql`
  copy:
    src:  Qiliasmaster.sql
    dest: /root/Qiliasmaster.sql
    owner: root
    mode: 0600
  become: yes

- name: Ensure mysql root password is updated for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock
    password: "{{ mysql.root_db_password }}"
    priv: '*.*:ALL,GRANT'
    check_implicit_admin: true
  loop: "{{ mysql.hosts }}"
  become: yes
  notify: restart mysql

- name: Create a new database with name 'ilias'
  mysql_db:
    name: ilias
    state: present
  register: database_exists

- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    name: ilias
    password: "{{ mysql.ilias_db_password}}"
    priv: 'ilias.*:ALL,GRANT'
    state: present


- name: Restore database
  mysql_db:
    name: ilias
    state: import
    target: /root/Qiliasmaster.sql
  when: database_exists.changed
